
server:
  port: 9003

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=PaymentDB
    username: SA
    password: Prince@10
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql:true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        
eureka:
  instance:
    #hostname: ${spring.application.name}
    prefer-ip-address: false 
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 10
    instance-info-replication-interval-seconds: 10
    service-url:
      defaultZone: ${EUREKA_DEFAULTZONE_URL:http://localhost:8761/eureka}
      
EUREKA_DEFAULTZONE_URL: http://localhost:8761/eureka




        
